# Generated by Django 3.2.9 on 2021-12-03 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('cost', models.IntegerField(null=True, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, default='no_image.png', null=True, upload_to='product_images/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=False)),
                ('is_moderated', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace1.category')),
            ],
            options={
                'verbose_name': 'Продукт(товар)',
                'verbose_name_plural': 'Продукты(товары)',
            },
        ),
    ]
