# Generated by Django 3.0.4 on 2020-03-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace1', '0003_product_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
