# Generated by Django 3.0.4 on 2020-03-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace1', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
