# Generated by Django 3.0.4 on 2020-03-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace1', '0006_auto_20200318_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adImages', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
