# Generated by Django 3.0.4 on 2020-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace1', '0007_auto_20200319_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adImages/', verbose_name='Изображение'),
        ),
    ]
