# Generated by Django 3.0.4 on 2020-03-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace1', '0011_auto_20200324_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'Подробности пользователя', 'verbose_name_plural': 'Подробности пользователя'},
        ),
    ]
