# Generated by Django 3.0.4 on 2020-03-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace1', '0012_auto_20200324_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user_id',
            new_name='user',
        ),
    ]
