# Generated by Django 2.2.11 on 2020-06-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace1', '0013_auto_20200324_2226'),
        ('marketplace1', '0009_auto_20200319_2121'),
    ]

    operations = [
    ]
